import numpy as np
import cv2
from scipy import ndimage

def calc_homo(matches1, matches2):
    H, _ = cv2.findHomography(matches1, matches2, 0)
    return H

def sam_mask_labeling(img1, img2, labels1, multi_homos, cell_matches):
    """
    Refine masks generated by SAM by cross-homography minimal error comparison.
    Simplified version of sammaskLabeling.m.
    """
    sz1, sz2 = labels1.shape
    num_H = len(multi_homos)
    
    if num_H == 0:
        return np.zeros_like(labels1), np.zeros((0, 9)), np.zeros_like(labels1, dtype=bool)

    X, Y = np.meshgrid(np.arange(sz2), np.arange(sz1))
    
    # non-overlapping region definition
    full_matches1 = []
    full_matches2 = []
    for m1, m2 in cell_matches:
        full_matches1.append(m1)
        full_matches2.append(m2)
    
    full_matches1 = np.vstack(full_matches1)
    full_matches2 = np.vstack(full_matches2)
    
    out_homo = calc_homo(full_matches1, full_matches2)
    
    map_XY = out_homo @ np.vstack((X.flatten(), Y.flatten(), np.ones(sz1*sz2)))
    map_XY = map_XY[:2, :] / map_XY[2, :]
    
    inner_index = (map_XY[0, :] >= 0) & (map_XY[0, :] < sz2) & \
                  (map_XY[1, :] >= 0) & (map_XY[1, :] < sz1)
    
    overlapped_mask1 = inner_index.reshape((sz1, sz2))
    
    refined_labels1 = np.zeros_like(labels1, dtype=np.int32)
    unique_labels = np.unique(labels1)
    
    for l in unique_labels:
        if l == 0: continue
        mask_i = (labels1 == l)
        tmpoverlap_mask_i = mask_i & overlapped_mask1
        
        if np.sum(tmpoverlap_mask_i) > 0:
            mask_i = tmpoverlap_mask_i
            x = X[mask_i]
            y = Y[mask_i]
            
            # Find best homography based on re-projection photometric error 
            # (In MATLAB, it does calcPhotometricError). For simplicity, we just use 
            # point distance if points exist, or evaluate median photometric error.
            mean_e = []
            for j in range(num_H):
                H = multi_homos[j].reshape(3,3)
                pts = np.vstack((x, y, np.ones_like(x)))
                w_pts = H @ pts
                w_pts = w_pts[:2, :] / (w_pts[2, :] + 1e-8)
                
                # compute photometric error
                # clip to valid indices
                valid = (w_pts[0, :] >= 0) & (w_pts[0, :] < sz2 - 1) & \
                        (w_pts[1, :] >= 0) & (w_pts[1, :] < sz1 - 1)
                        
                if np.sum(valid) == 0:
                    mean_e.append(float('inf'))
                    continue
                    
                w_x = w_pts[0, valid].astype(int)
                w_y = w_pts[1, valid].astype(int)
                
                orig_x = x[valid]
                orig_y = y[valid]
                
                color1 = img1[orig_y, orig_x]
                color2 = img2[w_y, w_x]
                
                err = np.mean(np.linalg.norm(color1 - color2, axis=1))
                mean_e.append(err)
                
            min_ind = np.argmin(mean_e)
            refined_labels1[mask_i] = min_ind + 1 # 1-based to distinguish from 0
            
    # For regions outside overlap, we extrapolate (simplified)
    final_labels1 = refined_labels1.copy()
    final_homos = multi_homos.copy()
    
    # ... In a full translation we would compute the Taylor series extrapolation 
    # for out-of-overlap regions. For now, we return the refined overlapping labels.
    
    return final_labels1, final_homos, overlapped_mask1
